package com.prettier.entity.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum CitiesOfTurkey {

    ADANA("ADANA", 1 ),
    ADIYAMAN("ADIYAMAN", 2 ),
    AFYON("AFYON", 3 ),
    AGRI("AĞRI", 4 ),
    AMASYA("AMASYA", 5 ),
    ANKARA("ANKARA", 6 ),
    ANTALYA("ANTALYA", 7 ),
    ARTVIN("ARTVİN", 8 ),
    AYDIN("AYDIN", 9 ),
    BALIKESIR("BALIKESİR", 10 ),
    BILECIK("BİLECİK", 11 ),
    BINGOL("BİNGÖL", 12 ),
    BITLIS("BİTLİS", 13 ),
    BOLU("BOLU", 14 ),
    BURDUR("BURDUR", 15 ),
    BURSA("BURSA", 16 ),
    CANAKKALE("ÇANAKKALE", 17 ),
    CANKIRI("ÇANKIRI", 18 ),
    CORUM("ÇORUM", 19 ),
    DENIZLI("DENİZLİ", 20 ),
    DIYARBAKIR("DİYARBAKIR", 21 ),
    EDIRNE("EDİRNE", 22 ),
    ELAZIG("ELAZIĞ", 23 ),
    ERZINCAN("ERZİNCAN", 24 ),
    ERZURUM("ERZURUM", 25 ),
    ESKISEHIR("ESKİŞEHİR", 26 ),
    GAZIANTEP("GAZİANTEP", 27 ),
    GIRESUN("GİRESUN", 28 ),
    GUMUSHANE("GÜMÜŞHANE", 29 ),
    HAKKARI("HAKKARİ", 30 ),
    HATAY("HATAY", 31 ),
    ISPARTA("ISPARTA", 32 ),
    ICEL("İÇEL", 33 ),
    ISTANBUL("İSTANBUL", 34 ),
    IZMIR("İZMİR", 35 ),
    KARS("KARS", 36 ),
    KASTAMONU("KASTAMONU", 37 ),
    KAYSERI("KAYSERİ", 38 ),
    KIRKLARELI("KIRKLARELİ", 39 ),
    KIRSEHIR("KIRŞEHİR", 40 ),
    KOCAELI("KOCAELİ", 41 ),
    KONYA("KONYA", 42 ),
    KUTAHYA("KÜTAHYA", 43 ),
    MALATYA("MALATYA", 44 ),
    MANISA("MANİSA", 45 ),
    KAHRAMANMARAS("KAHRAMANMARAŞ", 46 ),
    MARDIN("MARDİN", 47 ),
    MUGLA("MUĞLA", 48 ),
    MUS("MUŞ", 49 ),
    NEVSEHIR("NEVŞEHİR", 50 ),
    NIGDE("NİĞDE", 51 ),
    ORDU("ORDU", 52 ),
    RIZE("RİZE", 53 ),
    SAKARYA("SAKARYA", 54 ),
    SAMSUN("SAMSUN", 55 ),
    SIIRT("SİİRT", 56 ),
    SINOP("SİNOP", 57 ),
    SIVAS("SİVAS", 58 ),
    TEKIRDAG("TEKİRDAĞ", 59 ),
    TOKAT("TOKAT", 60 ),
    TRABZON("TRABZON", 61 ),
    TUNCELI("TUNCELİ", 62 ),
    SANLIURFA("ŞANLIURFA", 63 ),
    USAK("UŞAK", 64 ),
    VAN("VAN", 65 ),
    YOZGAT("YOZGAT", 66 ),
    ZONGULDAK("ZONGULDAK", 67 ),
    AKSARAY("AKSARAY", 68 ),
    BAYBURT("BAYBURT", 69 ),
    KARAMAN("KARAMAN", 70 ),
    KIRIKKALE("KIRIKKALE", 71 ),
    BATMAN("BATMAN", 72 ),
    SIRNAK("ŞIRNAK", 73 ),
    BARTIN("BARTIN", 74 ),
    ARDAHAN("ARDAHAN", 75 ),
    IGDIR("IĞDIR", 76 ),
    YALOVA("YALOVA", 77 ),
    KARABUK("KARABÜK", 78 ),
    KILIS("KİLİS", 79 ),
    OSMANIYE("OSMANİYE", 80 ),
    DUZCE("DÜZCE", 81);

    private final String cityName;
    private final Integer plateNumber;

}
