package com.prettier.entity.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Countries {

    Afghanistan("Afghanistan", "AF"),
    Aland_Islands("Aland Islands", "AX"),
    Albania("Albania", "AL"),
    Algeria("Algeria", "DZ"),
    American("American Samoa", "AS"),
    Andorra("Andorra", "AD"),
    Angola("Angola", "AO"),
    Anguilla("Anguilla", "AI"),
    Antarctica("Antarctica", "AQ"),
    Antigua_and_Barbuda("Antigua and Barbuda", "AG"),
    Argentina("Argentina", "AR"),
    Armenia("Armenia", "AM"),
    Aruba("Aruba", "AW"),
    Australia("Australia", "AU"),
    Austria("Austria", "AT"),
    Azerbaijan("Azerbaijan", "AZ"),
    Bahamas("Bahamas", "BS"),
    Bahrain("Bahrain", "BH"),
    Bangladesh("Bangladesh", "BD"),
    Barbados("Barbados", "BB"),
    Belarus("Belarus", "BY"),
    Belgium("Belgium", "BE"),
    Belize("Belize", "BZ"),
    Benin("Benin", "BJ"),
    Bermuda("Bermuda", "BM"),
    Bhutan("Bhutan", "BT"),
    Bolivia("Bolivia", "BO"),
    Bosnia_and_Herzegovina("Bosnia and Herzegovina", "BA"),
    Botswana("Botswana", "BW"),
    Bouvet_Island("Bouvet Island", "BV"),
    Brazil("Brazil", "BR"),
    British_Indian_Ocean_Territory("British Indian Ocean Territory", "IO"),
    Brunei_Darussalam("Brunei Darussalam", "BN"),
    Bulgaria("Bulgaria", "BG"),
    Burkina_Faso("Burkina Faso", "BF"),
    Burundi("Burundi", "BI"),
    Cambodia("Cambodia", "KH"),
    Cameroon("Cameroon", "CM"),
    Canada("Canada", "CA"),
    Cape_Verde("Cape Verde", "CV"),
    Cayman_Islands("Cayman Islands", "KY"),
    Central_African_Republic("Central African Republic", "CF"),
    Chad("Chad", "TD"),
    Chile("Chile", "CL"),
    China("China", "CN"),
    Christmas_Island("Christmas Island", "CX"),
    Cocos("Cocos (Keeling) Islands", "CC"),
    Colombia("Colombia", "CO"),
    Comoros("Comoros", "KM"),
    Congo("Congo", "CG"),
    Congo_The_Democratic_Republic_of_the("Congo, The Democratic Republic of the", "CD"),
    Cook_Islands("Cook Islands", "CK"),
    Costa_Rica("Costa Rica", "CR"),
    Cote_D("Cote D\"Ivoire", "CI"),
    Croatia("Croatia", "HR"),
    Cuba("Cuba", "CU"),
    Cyprus("Cyprus", "CY"),
    Czech_Republic("Czech Republic", "CZ"),
    Denmark("Denmark", "DK"),
    Djibouti("Djibouti", "DJ"),
    Dominica("Dominica", "DM"),
    Dominican_Republic("Dominican Republic", "DO"),
    Ecuador("Ecuador", "EC"),
    Egypt("Egypt", "EG"),
    El_Salvador("El Salvador", "SV"),
    Equatorial_Guinea("Equatorial Guinea", "GQ"),
    Eritrea("Eritrea", "ER"),
    Estonia("Estonia", "EE"),
    Ethiopia("Ethiopia", "ET"),
    Falkland_Islands("Falkland_Islands", "FK"),
    Faroe_Islands("Faroe Islands", "FO"),
    Fiji("Fiji", "FJ"),
    Finland("Finland", "FI"),
    France("France", "FR"),
    French_Guiana("French Guiana", "GF"),
    French_Polynesia("French Polynesia", "PF"),
    French_Southern_Territories("French Southern Territories", "TF"),
    Gabon("Gabon", "GA"),
    Gambia("Gambia", "GM"),
    Georgia("Georgia", "GE"),
    Germany("Germany", "DE"),
    Ghana("Ghana", "GH"),
    Gibraltar("Gibraltar", "GI"),
    Greece("Greece", "GR"),
    Greenland("Greenland", "GL"),
    Grenada("Grenada", "GD"),
    Guadeloupe("Guadeloupe", "GP"),
    Guam("Guam", "GU"),
    Guatemala("Guatemala", "GT"),
    Guernsey("Guernsey", "GG"),
    Guinea("Guinea", "GN"),
    Guinea_Bissau("Guinea-Bissau", "GW"),
    Guyana("Guyana", "GY"),
    Haiti("Haiti", "HT"),
    Heard_Island_and_Mcdonald_Islands("Heard Island and Mcdonald Islands", "HM"),
    Holy_See("Vatican City State", "VA"),
    Honduras("Honduras", "HN"),
    Hong_Kong("Hong Kong", "HK"),
    Hungary("Hungary", "HU"),
    Iceland("Iceland", "IS"),
    India("India", "IN"),
    Indonesia("Indonesia", "ID"),
    Iran("Iran, Islamic Republic Of", "IR"),
    Iraq("Iraq", "IQ"),
    Ireland("Ireland", "IE"),
    Isle_of_Man("Isle of Man", "IM"),
    Israel("Israel", "IL"),
    Italy("Italy", "IT"),
    Jamaica("Jamaica", "JM"),
    Japan("Japan", "JP"),
    Jersey("Jersey", "JE"),
    Jordan("Jordan", "JO"),
    Kazakhstan("Kazakhstan", "KZ"),
    Kenya("Kenya", "KE"),
    Kiribati("Kiribati", "KI"),
    Korea_Democratic_People("Korea, Democratic People\"S Republic of", "KP"),
    Korea_Republic_of("Korea, Republic of", "KR"),
    Kuwait("Kuwait", "KW"),
    Kyrgyzstan("Kyrgyzstan", "KG"),
    Lao_People("Lao People\"S Democratic Republic", "LA"),
    Latvia("Latvia", "LV"),
    Lebanon("Lebanon", "LB"),
    Lesotho("Lesotho", "LS"),
    Liberia("Liberia", "LR"),
    Libyan_Arab_Jamahiriya("Libyan Arab Jamahiriya", "LY"),
    Liechtenstein("Liechtenstein", "LI"),
    Lithuania("Lithuania", "LT"),
    Luxembourg("Luxembourg", "LU"),
    Macao("Macao", "MO"),
    Macedonia("Macedonia, The Former Yugoslav Republic of", "MK"),
    Madagascar("Madagascar", "MG"),
    Malawi("Malawi", "MW"),
    Malaysia("Malaysia", "MY"),
    Maldives("Maldives", "MV"),
    Mali("Mali", "ML"),
    Malta("Malta", "MT"),
    Marshall_Islands("Marshall Islands", "MH"),
    Martinique("Martinique", "MQ"),
    Mauritania("Mauritania", "MR"),
    Mauritius("Mauritius", "MU"),
    Mayotte("Mayotte", "YT"),
    Mexico("Mexico", "MX"),
    Micronesia("Micronesia, Federated States of", "FM"),
    Moldova("Moldova, Republic of", "MD"),
    Monaco("Monaco", "MC"),
    Mongolia("Mongolia", "MN"),
    Montserrat("Montserrat", "MS"),
    Morocco("Morocco", "MA"),
    Mozambique("Mozambique", "MZ"),
    Myanmar("Myanmar", "MM"),
    Namibia("Namibia", "NA"),
    Nauru("Nauru", "NR"),
    Nepal("Nepal", "NP"),
    Netherlands("Netherlands", "NL"),
    Netherlands_Antilles("Netherlands Antilles", "AN"),
    New_Caledonia("New Caledonia", "NC"),
    New_Zealand("New Zealand", "NZ"),
    Nicaragua("Nicaragua", "NI"),
    Niger("Niger", "NE"),
    Nigeria("Nigeria", "NG"),
    Niue("Niue", "NU"),
    Norfolk_Island("Norfolk Island", "NF"),
    Northern_Mariana_Islands("Northern Mariana Islands", "MP"),
    Norway("Norway", "NO"),
    Oman("Oman", "OM"),
    Pakistan("Pakistan", "PK"),
    Palau("Palau", "PW"),
    Palestinian_Territory("Palestinian Territory, Occupied", "PS"),
    Panama("Panama", "PA"),
    Papua_New_Guinea("Papua New Guinea", "PG"),
    Paraguay("Paraguay", "PY"),
    Peru("Peru", "PE"),
    Philippines("Philippines", "PH"),
    Pitcairn("Pitcairn", "PN"),
    Poland("Poland", "PL"),
    Portugal("Portugal", "PT"),
    Puerto_Rico("Puerto Rico", "PR"),
    Qatar("Qatar", "QA"),
    Reunion("Reunion", "RE"),
    Romania("Romania", "RO"),
    Russian_Federation("Russian Federation", "RU"),
    RWANDA("RWANDA", "RW"),
    Saint_Helena("Saint Helena", "SH"),
    Saint_Kitts_and_Nevis("Saint Kitts and Nevis", "KN"),
    Saint_Lucia("Saint Lucia", "LC"),
    Saint_Pierre_and_Miquelon("Saint Pierre and Miquelon", "PM"),
    Saint_Vincent_and_the_Grenadines("Saint Vincent and the Grenadines", "VC"),
    Samoa("Samoa", "WS"),
    San_Marino("San Marino", "SM"),
    Sao_Tome_and_Principe("Sao Tome and Principe", "ST"),
    Saudi_Arabia("Saudi Arabia", "SA"),
    Senegal("Senegal", "SN"),
    Serbia_and_Montenegro("Serbia and Montenegro", "CS"),
    Seychelles("Seychelles", "SC"),
    Sierra_Leone("Sierra Leone", "SL"),
    Singapore("Singapore", "SG"),
    Slovakia("Slovakia", "SK"),
    Slovenia("Slovenia", "SI"),
    Solomon_Islands("Solomon Islands", "SB"),
    Somalia("Somalia", "SO"),
    South_Africa("South Africa", "ZA"),
    South_Georgia_and_the_South_Sandwich_Islands("South Georgia and the South Sandwich Islands", "GS"),
    Spain("Spain", "ES"),
    Sri_Lanka("Sri Lanka", "LK"),
    Sudan("Sudan", "SD"),
    Suriname("Suriname", "SR"),
    Svalbard_and_Jan_Mayen("Svalbard and Jan Mayen", "SJ"),
    Swaziland("Swaziland", "SZ"),
    Sweden("Sweden", "SE"),
    Switzerland("Switzerland", "CH"),
    Syrian("Syrian Arab Republic", "SY"),
    Taiwan("Taiwan, Province of China", "TW"),
    Tajikistan("Tajikistan", "TJ"),
    Tanzania("Tanzania, United Republic of", "TZ"),
    Thailand("Thailand", "TH"),
    Timor_Leste("Timor-Leste", "TL"),
    Togo("Togo", "TG"),
    Tokelau("Tokelau", "TK"),
    Tonga("Tonga", "TO"),
    Trinidad_and_Tobago("Trinidad and Tobago", "TT"),
    Tunisia("Tunisia", "TN"),
    Turkey("Turkey", "TR"),
    Turkmenistan("Turkmenistan", "TM"),
    Turks_and_Caicos_Islands("Turks and Caicos Islands", "TC"),
    Tuvalu("Tuvalu", "TV"),
    Uganda("Uganda", "UG"),
    Ukraine("Ukraine", "UA"),
    United_Arab_Emirates("United Arab Emirates", "AE"),
    United_Kingdom("United Kingdom", "GB"),
    United_States("United States", "US"),
    United_States_Minor_Outlying_Islands("United States Minor Outlying Islands", "UM"),
    Uruguay("Uruguay", "UY"),
    Uzbekistan("Uzbekistan", "UZ"),
    Vanuatu("Vanuatu", "VU"),
    Venezuela("Venezuela", "VE"),
    Viet_Nam("Viet Nam", "VN"),
    Virgin_Islands_British("Virgin Islands, British", "VG"),
    Virgin_Islands_U_S("Virgin Islands, U.S.", "VI"),
    Wallis_and_Futuna("Wallis and Futuna", "WF"),
    Western_Sahara("Western Sahara", "EH"),
    Yemen("Yemen", "YE"),
    Zambia("Zambia", "ZM"),
    Zimbabwe("Zimbabwe", "ZW");

    private final String name;
    private final String code;


}
